import React, { createContext, useContext, useState } from 'react';
import { ApiKey, Webhook, WebhookEvent, WebhookLog } from '../types';
import { useAuth } from './AuthContext';

interface IntegrationContextType {
  apiKeys: ApiKey[];
  webhooks: Webhook[];
  webhookLogs: WebhookLog[];
  createApiKey: (name: string, scopes: ApiKey['scopes']) => string; // Returns the full key once
  revokeApiKey: (id: string) => void;
  createWebhook: (url: string, events: WebhookEvent[]) => void;
  updateWebhook: (id: string, updates: Partial<Webhook>) => void;
  deleteWebhook: (id: string) => void;
  triggerTestEvent: (webhookId: string) => Promise<void>;
}

const IntegrationContext = createContext<IntegrationContextType | undefined>(undefined);

export const IntegrationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user, logAction } = useAuth();

  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [webhooks, setWebhooks] = useState<Webhook[]>([]);
  const [webhookLogs, setWebhookLogs] = useState<WebhookLog[]>([]);

  const orgApiKeys = apiKeys.filter(k => k.org_id === user?.org_id);
  const orgWebhooks = webhooks.filter(w => w.org_id === user?.org_id);

  const createApiKey = (name: string, scopes: ApiKey['scopes']): string => {
    if (!user) throw new Error("Not authenticated");
    
    // Generate mock key
    const fullKey = `pk_live_${Math.random().toString(36).substr(2, 24)}`;
    const prefix = `${fullKey.substr(0, 8)}...${fullKey.substr(fullKey.length - 4)}`;
    
    const newKey: ApiKey = {
        id: `key_${Math.random().toString(36).substr(2, 9)}`,
        org_id: user.org_id,
        name,
        prefix,
        key_hash: 'mock_hash', // In real app, hash the key
        scopes,
        status: 'active',
        created_at: new Date().toISOString()
    };

    setApiKeys(prev => [newKey, ...prev]);
    logAction('CREATE_API_KEY', 'API_KEY', newKey.id, { name, scopes });
    return fullKey;
  };

  const revokeApiKey = (id: string) => {
    setApiKeys(prev => prev.map(k => k.id === id ? { ...k, status: 'revoked' } : k));
    logAction('REVOKE_API_KEY', 'API_KEY', id);
  };

  const createWebhook = (url: string, events: WebhookEvent[]) => {
      if (!user) return;
      const newHook: Webhook = {
          id: `wh_${Math.random().toString(36).substr(2, 9)}`,
          org_id: user.org_id,
          url,
          events,
          secret: `whsec_${Math.random().toString(36).substr(2, 16)}`,
          status: 'active',
          created_at: new Date().toISOString(),
          failure_count: 0
      };
      setWebhooks(prev => [newHook, ...prev]);
      logAction('CREATE_WEBHOOK', 'WEBHOOK', newHook.id, { url, events });
  };

  const updateWebhook = (id: string, updates: Partial<Webhook>) => {
      setWebhooks(prev => prev.map(w => w.id === id ? { ...w, ...updates } : w));
      logAction('UPDATE_WEBHOOK', 'WEBHOOK', id, { updates });
  };

  const deleteWebhook = (id: string) => {
      setWebhooks(prev => prev.filter(w => w.id !== id));
      logAction('DELETE_WEBHOOK', 'WEBHOOK', id);
  };

  const triggerTestEvent = async (webhookId: string) => {
      const hook = webhooks.find(w => w.id === webhookId);
      if (!hook) return;

      // Simulate network request
      const success = Math.random() > 0.2; // 80% success rate mock
      const status = success ? 200 : 500;
      
      const newLog: WebhookLog = {
          id: `log_${Math.random().toString(36).substr(2, 9)}`,
          webhook_id: webhookId,
          event_type: hook.events[0] || 'ping',
          payload: {
              event: hook.events[0] || 'ping',
              data: {
                  id: 'bill_test_123',
                  status: 'completed',
                  meta: 'This is a test event generated by the user.'
              },
              timestamp: new Date().toISOString()
          },
          status_code: status,
          response_body: success ? '{"received": true}' : 'Internal Server Error',
          timestamp: new Date().toISOString()
      };

      setWebhookLogs(prev => [newLog, ...prev]);
      
      if (!success) {
          updateWebhook(webhookId, { failure_count: hook.failure_count + 1 });
      }
  };

  return (
    <IntegrationContext.Provider value={{ 
        apiKeys: orgApiKeys, 
        webhooks: orgWebhooks, 
        webhookLogs,
        createApiKey, 
        revokeApiKey, 
        createWebhook, 
        updateWebhook, 
        deleteWebhook,
        triggerTestEvent
    }}>
      {children}
    </IntegrationContext.Provider>
  );
};

export const useIntegration = () => {
  const context = useContext(IntegrationContext);
  if (context === undefined) {
    throw new Error('useIntegration must be used within an IntegrationProvider');
  }
  return context;
};
